name: Build

on:
  push:
    branches: [ main ]
#  schedule:
#  - cron:  '*/15 * * * *'

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Get Maven Url
      run: |
        echo "MAVEN_URL=$(gcloud artifacts print-settings gradle --project ${{ secrets.GCP_PROJECT_ID }} --repository ${{ secrets.GCP_ARTIFACT_REPO }} --location ${{ secrets.GCP_LOCATION }} | grep url | sed 's/.*"\([^"]\+\)"/\1/' | uniq)" >> $GITHUB_ENV
    - name: Get Maven Password
      run: |
        echo "MAVEN_PASSWORD=$(gcloud artifacts print-settings gradle --project ${{ secrets.GCP_PROJECT_ID }} --repository ${{ secrets.GCP_ARTIFACT_REPO }} --location ${{ secrets.GCP_LOCATION }} | grep "def artifactRegistryMavenSecret" | sed 's/.*"\([^"]\+\)"/\1/')" >> $GITHUB_ENV
        echo ::add-mask::${MAVEN_PASSWORD}
    - name: Build  
      run: ./build.sh
      env:
        MAVEN_URL: ${{ env.MAVEN_URL }}
        MAVEN_USERNAME: _json_key_base64
        MAVEN_PASSWORD: ${{ env.MAVEN_PASSWORD }}
        SHOULD_PUBLISH: ${{ secrets.SHOULD_PUBLISH }}