name: Build

on:
  push:
    branches: [ main ]
#  schedule:
#  - cron:  '*/15 * * * *'

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: ./build.sh
      env:
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        SHOULD_PUBLISH: ${{ secrets.SHOULD_PUBLISH }}