name: Build

on:
  push:
    branches: [ main ]
#  schedule:
#  - cron:  '*/15 * * * *'

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Get Maven Url
      run: echo "MAVEN_URL=$(aws codeartifact get-repository-endpoint --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --repository ${{ secrets.CODEARTIFACT_REPOSITORY }} --format maven --query repositoryEndpoint --output text)" >> $GITHUB_ENV
    - name: Get Maven Password
      run: echo "MAVEN_PASSWORD=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --query authorizationToken --output text)" >> $GITHUB_ENV
    - name: Build  
      run: ./build.sh
      env:
        MAVEN_URL: ${{ env.MAVEN_URL }}
        MAVEN_USERNAME: aws
        MAVEN_PASSWORD: ${{ env.MAVEN_PASSWORD }}
        SHOULD_PUBLISH: ${{ secrets.SHOULD_PUBLISH }}